// web_src/js/webcomponents/context-popup.ts
// ContextPopup Web Component
// Simple issue preview popup - converted from Vue component

type IssueData = {
  repository: {
    full_name: string;
  };
  created_at: string;
  body: string;
  html_url: string;
  title: string;
  number: number;
  labels: Array<{name: string; color: string; url: string}>;
};

type ContextPopupLocale = {
  errorMessage?: string;
};

class ContextPopup extends HTMLElement {
  #issue: IssueData | null = null;
  #renderedLabels = '';
  #errorMessage = '';
  #locale: ContextPopupLocale = {};

  static get observedAttributes(): string[] {
    return ['data-issue', 'data-rendered-labels', 'data-error-message', 'data-locale'];
  }

  attributeChangedCallback(name: string, _old: string, newVal: string): void {
    if (name === 'data-issue' && newVal) {
      try {
        this.#issue = JSON.parse(newVal);
      } catch {
        this.#issue = null;
      }
    } else if (name === 'data-rendered-labels') {
      this.#renderedLabels = newVal;
    } else if (name === 'data-error-message') {
      this.#errorMessage = newVal;
    } else if (name === 'data-locale' && newVal) {
      try {
        this.#locale = JSON.parse(newVal);
      } catch {
        this.#locale = {};
      }
    }
    this.#render();
  }

  connectedCallback(): void {
    this.#render();
  }

  #render(): void {
    const appSubUrl = (window as any).config?.appSubUrl || '';

    const styles = `
      <style>
        .context-popup { padding: 1rem; max-width: 400px; }
        .context-popup .repo-name { font-size: 0.75rem; color: var(--color-text-light-2); margin-bottom: 0.5rem; }
        .context-popup .repo-name a { color: inherit; text-decoration: none; }
        .context-popup .issue-header { display: flex; align-items: flex-start; gap: 0.5rem; margin-bottom: 0.5rem; }
        .context-popup .issue-icon { flex-shrink: 0; width: 16px; height: 16px; }
        .context-popup .issue-title { font-weight: 600; word-break: break-word; color: inherit; text-decoration: none; }
        .context-popup .issue-title:hover { color: var(--color-primary); }
        .context-popup .issue-index { color: var(--color-text-light-1); }
        .context-popup .issue-body { font-size: 0.875rem; color: var(--color-text-light-1); margin-bottom: 0.5rem; }
        .context-popup .issue-labels { display: flex; flex-wrap: wrap; gap: 0.25rem; }
        .context-popup .error-message { color: var(--color-error-text); padding: 1rem; text-align: center; }
      </style>
    `;

    let content = '';

    let createdAt = '';
    if (this.#issue) {
      createdAt = new Date(this.#issue.created_at).toLocaleDateString(undefined, {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      });

      const body = this.#issue.body.replace(/\n+/g, ' ');
      const truncatedBody = body.length > 85 ? `${body.substring(0, 85)}…` : body;

      const issueIcon = this.#getIssueIcon(this.#issue);
      const issueColorClass = this.#getIssueColorClass(this.#issue);

      content = `
        <div class="issue-header">
          <svg-icon name="${issueIcon}" class="issue-icon ${issueColorClass}"></svg-icon>
          <a href="${escapeHtml(this.#issue.html_url)}" class="issue-title">
            ${escapeHtml(this.#issue.title)}
            <span class="issue-index">#${this.#issue.number}</span>
          </a>
        </div>
        ${truncatedBody ? `<div class="issue-body">${escapeHtml(truncatedBody)}</div>` : ''}
        ${this.#renderedLabels ? `<div class="issue-labels">${this.#renderedLabels}</div>` : ''}
      `;
    } else if (this.#errorMessage) {
      content = `<div class="error-message">${escapeHtml(this.#errorMessage)}</div>`;
    } else {
      content = `<div class="error-message">${this.#locale.errorMessage || 'Failed to load issue'}</div>`;
    }

    const template = `
      <div class="context-popup">
        ${this.#issue ? `
          <div class="repo-name">
            <a href="${escapeHtml(`${appSubUrl}/${this.#issue.repository.full_name}`)}">${escapeHtml(this.#issue.repository.full_name)}</a>
            on ${createdAt}
          </div>
        ` : ''}
        ${content}
      </div>
    `;

    this.shadowRoot!.innerHTML = styles + template;
  }

  #getIssueIcon(_issue: IssueData): string {
    // Simplified - in the original this came from a separate module
    // Default to octicon-issue-opened for open issues
    return 'octicon-issue-opened';
  }

  #getIssueColorClass(_issue: IssueData): string {
    // Simplified - in the original this came from a separate module
    return 'tw-text-green';
  }
}

// @ts-ignore: Duplicate function implementation (false positive)
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

if (!customElements.get('context-popup')) {
  customElements.define('context-popup', ContextPopup);
}

// web_src/js/components/ContextPopup.vue
<script lang="ts" setup>
import {SvgIcon} from '../svg.ts';
import {GET} from '../modules/fetch.ts';
import {computed, onMounted, ref} from 'vue';
import type {Issue} from '../types';

const {appSubUrl, i18n} = window.config;

const loading = ref(false);
const issue = ref(null);
const renderedLabels = ref('');
const i18nErrorOccurred = i18n.error_occurred;
const i18nErrorMessage = ref(null);

const createdAt = computed(() => new Date(issue.value.created_at).toLocaleDateString(undefined, {year: 'numeric', month: 'short', day: 'numeric'}));
const body = computed(() => {
  const body = issue.value.body.replace(/\n+/g, ' ');
  if (body.length > 85) {
    return `${body.substring(0, 85)}…`;
  }
  return body;
});

function getIssueIcon(issue: Issue) {
  if (issue.pull_request) {
    if (issue.state === 'open') {
      if (issue.pull_request.draft === true) {
        return 'octicon-git-pull-request-draft'; // WIP PR
      }
      return 'octicon-git-pull-request'; // Open PR
    } else if (issue.pull_request.merged === true) {
      return 'octicon-git-merge'; // Merged PR
    }
    return 'octicon-git-pull-request'; // Closed PR
  } else if (issue.state === 'open') {
    return 'octicon-issue-opened'; // Open Issue
  }
  return 'octicon-issue-closed'; // Closed Issue
}

function getIssueColor(issue: Issue) {
  if (issue.pull_request) {
    if (issue.pull_request.draft === true) {
      return 'grey'; // WIP PR
    } else if (issue.pull_request.merged === true) {
      return 'purple'; // Merged PR
    }
  }
  if (issue.state === 'open') {
    return 'green'; // Open Issue
  }
  return 'red'; // Closed Issue
}

const root = ref<HTMLElement | null>(null);

onMounted(() => {
  root.value.addEventListener('ce-load-context-popup', (e: CustomEvent) => {
    const data = e.detail;
    if (!loading.value && issue.value === null) {
      load(data);
    }
  });
});

async function load(data) {
  loading.value = true;
  i18nErrorMessage.value = null;

  try {
    const response = await GET(`${appSubUrl}/${data.owner}/${data.repo}/issues/${data.index}/info`); // backend: GetIssueInfo
    const respJson = await response.json();
    if (!response.ok) {
      i18nErrorMessage.value = respJson.message ?? i18n.network_error;
      return;
    }
    issue.value = respJson.convertedIssue;
    renderedLabels.value = respJson.renderedLabels;
  } catch {
    i18nErrorMessage.value = i18n.network_error;
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div ref="root">
    <div v-if="loading" class="tw-h-12 tw-w-12 is-loading"/>
    <div v-if="!loading && issue !== null" class="tw-flex tw-flex-col tw-gap-2">
      <div class="tw-text-12">{{ issue.repository.full_name }} on {{ createdAt }}</div>
      <div class="flex-text-block">
        <svg-icon :name="getIssueIcon(issue)" :class="['text', getIssueColor(issue)]"/>
        <span class="issue-title tw-font-semibold tw-break-anywhere">
          {{ issue.title }}
          <span class="index">#{{ issue.number }}</span>
        </span>
      </div>
      <div v-if="body">{{ body }}</div>
      <!-- eslint-disable-next-line vue/no-v-html -->
      <div v-if="issue.labels.length" v-html="renderedLabels"/>
    </div>
    <div class="tw-flex tw-flex-col tw-gap-2" v-if="!loading && issue === null">
      <div class="tw-text-12">{{ i18nErrorOccurred }}</div>
      <div>{{ i18nErrorMessage }}</div>
    </div>
  </div>
</template>
